import React, { useEffect, useState } from 'react';
import supabase from '../../conexao/conexao';

/*
create table public.tb_moldes (
  id bigint generated by default as identity not null,
  "codMoldeExterno" text null,
  "descMolde" text null,
  "phMolde" smallint null,
  "pesoMolde" smallint not null,
  updated_at timestamp with time zone null default now(),
  created_at timestamp with time zone not null default now(),
  constraint tb_moldes_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tb_recursos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  "tipoRecurso" public.tipo_recurso_enum not null,
  recurso_id bigint not null,
  observacao text null,
  constraint tb_recursos_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tb_maquinas (
  id bigint generated by default as identity not null,
  "codMaquina" text null,
  "descMaquina" text null,
  "statusMaquina" text null,
  "tipoMaquina" text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  constraint tb_Maquinas_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tb_ordemservico (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  maquina_id smallint null,
  usuario_id smallint null,
  "dataAbertura" timestamp with time zone null,
  "dataPrevisao" timestamp with time zone null,
  "statusOS" text null,
  "descOS" text null,
  constraint tb_ordemservico_pkey primary key (id)
) TABLESPACE pg_default;
*/

export default function CadastroRecurso() {
  const [tipo, setTipo] = useState('molde');

  const [descMolde, setDescMolde] = useState('');
  const [pesoMolde, setPesoMolde] = useState('');
  const [phMolde, setPhMolde] = useState('');

  const [descMaquina, setDescMaquina] = useState('');
  const [statusMaquina, setStatusMaquina] = useState('');
  const [tipoMaquina, setTipoMaquina] = useState('');

  const [recursos, setRecursos] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [editingResource, setEditingResource] = useState(null);

  useEffect(() => {
    carregarRecursos();
  }, []);

  const carregarRecursos = async () => {
    setIsLoading(true);
    try {
      const { data: moldes, error: moldesError } = await supabase.from('tb_moldes').select('*');
      const { data: maquinas, error: maquinasError } = await supabase.from('tb_maquinas').select('*');

      if (moldesError) throw moldesError;
      if (maquinasError) throw maquinasError;

      const moldesFormatados = (moldes || []).map((item) => ({
        id: item.id,
        tipo: 'molde',
        descMolde: item.descMolde || '',
        pesoMolde: item.pesoMolde || '',
        phMolde: item.phMolde || '',
      }));

      const maquinasFormatadas = (maquinas || []).map((item) => ({
        id: item.id,
        tipo: 'maquina',
        descMaquina: item.descMaquina || '',
        statusMaquina: item.statusMaquina || '',
        tipoMaquina: item.tipoMaquina || '',
      }));

      setRecursos([...moldesFormatados, ...maquinasFormatadas]);
    } catch (error) {
      console.error('Erro ao carregar recursos:', error);
      alert('Não foi possível carregar os recursos.');
    } finally {
      setIsLoading(false);
    }
  };

  const limparFormulario = () => {
    setEditingResource(null);
    setTipo('molde');
    setDescMolde('');
    setPesoMolde('');
    setPhMolde('');
    setDescMaquina('');
    setStatusMaquina('');
    setTipoMaquina('');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      if (tipo === 'molde') {
        if (editingResource && editingResource.tipo === 'molde') {
          const { error } = await supabase
            .from('tb_moldes')
            .update({
              descMolde,
              pesoMolde: Number(pesoMolde) || null,
              phMolde: phMolde ? Number(phMolde) : null,
            })
            .eq('id', editingResource.id);

          if (error) throw error;
          alert('Molde atualizado com sucesso!');
        } else {
          const { error } = await supabase.from('tb_moldes').insert([
            {
              descMolde,
              pesoMolde: Number(pesoMolde) || null,
              phMolde: phMolde ? Number(phMolde) : null,
            },
          ]);

          if (error) throw error;
          alert('Molde cadastrado com sucesso!');
        }
      } else {
        if (editingResource && editingResource.tipo === 'maquina') {
          const { error } = await supabase
            .from('tb_maquinas')
            .update({
              descMaquina,
              statusMaquina,
              tipoMaquina,
            })
            .eq('id', editingResource.id);

          if (error) throw error;
          alert('Máquina atualizada com sucesso!');
        } else {
          const { error } = await supabase.from('tb_maquinas').insert([
            {
              descMaquina,
              statusMaquina,
              tipoMaquina,
            },
          ]);

          if (error) throw error;
          alert('Máquina cadastrada com sucesso!');
        }
      }

      limparFormulario();
      carregarRecursos();
    } catch (err) {
      console.error('Erro ao salvar recurso:', err);
      alert('Erro ao salvar recurso. Confira os dados e tente novamente.');
    }
  };

  const handleEditar = (recurso) => {
    setEditingResource(recurso);
    setTipo(recurso.tipo);

    if (recurso.tipo === 'molde') {
      setDescMolde(recurso.descMolde);
      setPesoMolde(recurso.pesoMolde || '');
      setPhMolde(recurso.phMolde || '');
      setDescMaquina('');
      setStatusMaquina('');
      setTipoMaquina('');
    } else {
      setDescMaquina(recurso.descMaquina);
      setStatusMaquina(recurso.statusMaquina);
      setTipoMaquina(recurso.tipoMaquina);
      setDescMolde('');
      setPesoMolde('');
      setPhMolde('');
    }
  };

  const handleExcluir = async (recurso) => {
    if (!window.confirm(`Deseja excluir este ${recurso.tipo === 'molde' ? 'molde' : 'máquina'}?`)) {
      return;
    }

    try {
      if (recurso.tipo === 'molde') {
        const { error } = await supabase.from('tb_moldes').delete().eq('id', recurso.id);
        if (error) throw error;
      } else {
        const { error } = await supabase.from('tb_maquinas').delete().eq('id', recurso.id);
        if (error) throw error;
      }

      alert('Recurso excluído com sucesso!');
      carregarRecursos();
      if (editingResource?.id === recurso.id && editingResource?.tipo === recurso.tipo) {
        limparFormulario();
      }
    } catch (error) {
      console.error('Erro ao excluir recurso:', error);
      alert('Erro ao excluir recurso. Tente novamente.');
    }
  };

  return (
    <>
      <h1>Recursos</h1>

      <form onSubmit={handleSubmit} style={{ marginBottom: '24px' }}>
        <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
          <label>
            Tipo de Recurso:
            <select value={tipo} onChange={(e) => setTipo(e.target.value)} style={{ marginLeft: '8px' }}>
              <option value="molde">Molde</option>
              <option value="maquina">Máquina</option>
            </select>
          </label>

          {tipo === 'molde' && (
            <>
              <input
                placeholder="Descrição do Molde"
                value={descMolde}
                onChange={(e) => setDescMolde(e.target.value)}
              />
              <input
                placeholder="Peso do Molde"
                type="number"
                value={pesoMolde}
                onChange={(e) => setPesoMolde(e.target.value)}
              />
              <input
                placeholder="PH do Molde"
                type="number"
                value={phMolde}
                onChange={(e) => setPhMolde(e.target.value)}
              />
            </>
          )}

          {tipo === 'maquina' && (
            <>
              <input
                placeholder="Descrição da Máquina"
                value={descMaquina}
                onChange={(e) => setDescMaquina(e.target.value)}
              />
              <input
                placeholder="Status da Máquina"
                value={statusMaquina}
                onChange={(e) => setStatusMaquina(e.target.value)}
              />
              <input
                placeholder="Tipo da Máquina"
                value={tipoMaquina}
                onChange={(e) => setTipoMaquina(e.target.value)}
              />
            </>
          )}
        </div>

        <div style={{ marginTop: '16px', display: 'flex', gap: '12px' }}>
          <button type="submit">{editingResource ? 'Atualizar' : 'Salvar'}</button>
          {editingResource && (
            <button type="button" onClick={limparFormulario} style={{ backgroundColor: '#999', color: '#fff' }}>
              Cancelar edição
            </button>
          )}
        </div>
      </form>

      <section>
        <h2>Lista de Recursos</h2>

        {isLoading ? (
          <p>Carregando recursos...</p>
        ) : recursos.length === 0 ? (
          <p>Nenhum recurso cadastrado ainda.</p>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr>
                <th style={{ borderBottom: '1px solid #ccc', padding: '8px' }}>Tipo</th>
                <th style={{ borderBottom: '1px solid #ccc', padding: '8px' }}>Descrição</th>
                <th style={{ borderBottom: '1px solid #ccc', padding: '8px' }}>Peso</th>
                <th style={{ borderBottom: '1px solid #ccc', padding: '8px' }}>PH</th>
                <th style={{ borderBottom: '1px solid #ccc', padding: '8px' }}>Status</th>
                <th style={{ borderBottom: '1px solid #ccc', padding: '8px' }}>Tipo Máquina</th>
                <th style={{ borderBottom: '1px solid #ccc', padding: '8px' }}>Ações</th>
              </tr>
            </thead>
            <tbody>
              {recursos.map((recurso) => (
                <tr key={`${recurso.tipo}-${recurso.id}`}>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {recurso.tipo === 'molde' ? 'Molde' : 'Máquina'}
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {recurso.tipo === 'molde' ? recurso.descMolde : recurso.descMaquina}
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {recurso.tipo === 'molde' ? recurso.pesoMolde : '—'}
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {recurso.tipo === 'molde' ? recurso.phMolde : '—'}
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {recurso.tipo === 'maquina' ? recurso.statusMaquina : '—'}
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {recurso.tipo === 'maquina' ? recurso.tipoMaquina : '—'}
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    <button onClick={() => handleEditar(recurso)} style={{ marginRight: '8px' }}>
                      Editar
                    </button>
                    <button onClick={() => handleExcluir(recurso)} style={{ backgroundColor: '#c00', color: '#fff' }}>
                      Excluir
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>
    </>
  );
}
